# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

updates:

  - package-ecosystem: "maven"
    directory: "/classloader/"
    target-branch: "master"
    schedule:
      interval: "daily"
      time: "01:00"
      timezone: "Europe/Berlin"
    rebase-strategy: "disabled"

  - package-ecosystem: "maven"
    directory: "/generic-code/"
    target-branch: "master"
    schedule:
      interval: "daily"
      time: "01:00"
      timezone: "Europe/Berlin"
    rebase-strategy: "disabled"

  - package-ecosystem: "maven"
    directory: "/logging/"
    target-branch: "master"
    schedule:
      interval: "daily"
      time: "01:00"
      timezone: "Europe/Berlin"
    rebase-strategy: "disabled"

  - package-ecosystem: "maven"
    directory: "/streams-distinct-by-property/"
    target-branch: "master"
    schedule:
      interval: "daily"
      time: "01:00"
      timezone: "Europe/Berlin"
    rebase-strategy: "disabled"

  - package-ecosystem: "maven"
    directory: "/tree-structure/"
    target-branch: "master"
    schedule:
      interval: "daily"
      time: "01:00"
      timezone: "Europe/Berlin"
    rebase-strategy: "disabled"
